import { index, integer, primaryKey, sqliteTable, text, unique } from "drizzle-orm/sqlite-core";

// Better Auth tables (user, session, account, verification) are generated by
// @nuxtjs/better-auth and merged into the NuxtHub schema automatically.

// A league is a night, gender and age group, e.g. Friday co-ed adults. Pages link by slug: /friday-coed/matches.
export const leagues = sqliteTable("leagues", {
	id: integer().primaryKey({ autoIncrement: true }),
	slug: text().notNull().unique(), // "friday-coed"
	name: text().notNull(), // "Friday Co-ed"
	// Which playoff function resolves the bracket (playoffFormats in server/utils/season.ts), so one league's format can change without the other's
	playoffFormat: text({ enum: ["six-team", "eight-team"] }).notNull(),
});

// A league's newest season (by name) is its current one.
export const seasons = sqliteTable(
	"seasons",
	{
		id: integer().primaryKey({ autoIncrement: true }),
		leagueId: integer()
			.notNull()
			.references(() => leagues.id),
		name: text().notNull(), // "2025/2026"
	},
	(t) => [unique().on(t.leagueId, t.name)],
);

// A team exists for one season: its captain's name plus a jersey color.
export const teams = sqliteTable(
	"teams",
	{
		id: integer().primaryKey({ autoIncrement: true }),
		seasonId: integer()
			.notNull()
			.references(() => seasons.id),
		name: text().notNull(), // captain, e.g. "Patrick"
		color: text().notNull(), // "Yellow"
	},
	(t) => [unique().on(t.seasonId, t.color)],
);

// A player is a person across seasons; which team they played for lives in `rosters`.
export const players = sqliteTable("players", {
	id: integer().primaryKey({ autoIncrement: true }),
	firstName: text().notNull(),
	lastName: text().notNull(),
	imageKey: text(), // blob (R2) pathname
});

export const rosters = sqliteTable(
	"rosters",
	{
		seasonId: integer()
			.notNull()
			.references(() => seasons.id),
		playerId: integer()
			.notNull()
			.references(() => players.id),
		teamId: integer()
			.notNull()
			.references(() => teams.id),
	},
	// One team per player per season
	(t) => [primaryKey({ columns: [t.seasonId, t.playerId] })],
);

export const matches = sqliteTable(
	"matches",
	{
		id: integer().primaryKey({ autoIncrement: true }),
		code: text().notNull().unique(), // legacy matchId, e.g. "252601"
		seasonId: integer()
			.notNull()
			.references(() => seasons.id),
		// Local wall-clock time, no offset (e.g. "2025-10-24T19:30:00"). Workers run in UTC,
		// so never convert through Date/timestamps on the server.
		startsAt: text().notNull(),
		// Playoff games can be scheduled before teams are known: the team id is null and
		// the slot holds the placeholder ("3rd", "Highest seed", "Finals").
		homeTeamId: integer().references(() => teams.id),
		awayTeamId: integer().references(() => teams.id),
		homeSlot: text(),
		awaySlot: text(),
		homeScore: integer(),
		awayScore: integer(),
		isPlayoff: integer({ mode: "boolean" }).notNull().default(false),
	},
	// Pages load one season's matches in date order
	(t) => [index("matches_season_id_starts_at_idx").on(t.seasonId, t.startsAt)],
);
